apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/demo
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: eso
  healthChecks:
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      name: demo-config
      namespace: demo
