apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./platform/postgres
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
    - name: cnpg
    - name: cnpg-barman-plugin
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: openbao-postgres
      namespace: openbao
  decryption:
    provider: sops
    secretRef:
      name: sops-age
