apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao
spec:
  provider:
    vault:
      server: "https://openbao.openbao.svc.cluster.local:8200"
      path: secret
      version: v2
      caProvider:
        type: Secret
        name: openbao-platform-root-ca-secret
        namespace: cert-manager
        key: ca.crt
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso-role
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
