apiVersion: v1
kind: Secret
metadata:
  name: backup-credentials
  namespace: openbao
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:8pc2vtGaJG2pzdp0IKYuMUO6kX4=,iv:v0ba+6S9X4P7lRszgsCz8xn+vcOUrNDbjMAY90V5L4k=,tag:5H2Bt5T8gBCfJfNJtQEEhA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:DK1OS9lKXohE3ae/keaiuvIhI/kSceSgaNz2HquS/A8MleD+McWGXg==,iv:oTP7YfDO+iUAIkOMvnbUMiKwjJ1/QKPJ+sBNl2l2//U=,tag:SeckpiGmNdYcrBVp3nHC1A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaVZPSG4xS3FkQUswRnhw
        SU1oM3ZnSUlTQ0puWnlkb0RGZkU4UUdlK0V3Cnp3OHBEeWZ0MDFBS0lFR3g3eFVB
        NXl1U1V5VWV5a2N5U3RkL3pKYi9TMWcKLS0tIFozOEh5NU52TFkyeE15U0orYjV2
        US9EZWdpbmhXV2traHRRelAwUktQTDgKWBJ82nMiv49keIuLJz48ZkDztG9Wr7TO
        8v9k3ttA84A11Fvq+wXwvTluciwFRXGF562ghyqsymvoAxHhCxSurA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nmpdy4lpklsd4uf9vq7vr5csf5s4q8qs27t0sr4u34t4pxvn5drquch82j
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-30T10:08:02Z"
  mac: ENC[AES256_GCM,data:h/fv8AQczQ0AxfykmQRtVcWIULTNOLxyxY5x1uKGjWxjou174tHSeRbe9imzf4zdLDVtXsKb79/U3cC2M7mudpFoZF4/jdvxG3AMeImrtwKz0EEiWfTLRSSUgqLdu4bBSoWmfm5dpDoJNydVG80nuOpKcrf8zxIzhV+ZFixc9PI=,iv:yAP68zIsRyExZtj12zuDo2+JpdoQnfGtw3GRe0KSDFY=,tag:6Nokdd7SkSqqp1Ce2P4BVg==,type:str]
  version: 3.13.3
