apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: openbao-postgres-daily
  namespace: openbao
spec:
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: openbao-postgres
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
