apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-config
  namespace: demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: demo-config
    creationPolicy: Owner
  data:
    - secretKey: message
      remoteRef:
        key: demo/config
        property: message
